# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expenses_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 408)
        Form.setMaximumSize(QtCore.QSize(381, 408))
        Form.setStyleSheet("background-color: #021c1e")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(80)
        self.verticalLayout.setObjectName("verticalLayout")
        self.amount_exp = QtWidgets.QLineEdit(Form)
        self.amount_exp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_exp.sizePolicy().hasHeightForWidth())
        self.amount_exp.setSizePolicy(sizePolicy)
        self.amount_exp.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amount_exp.setFont(font)
        self.amount_exp.setStyleSheet("border: 2px solid transparent;\n"
"border-bottom: 2px ridge #6fb98f;\n"
"color: white;\n"
"height: 30")
        self.amount_exp.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_exp.setObjectName("amount_exp")
        self.verticalLayout.addWidget(self.amount_exp, 0, QtCore.Qt.AlignHCenter)
        self.exp_category_list = QtWidgets.QListWidget(Form)
        self.exp_category_list.setEnabled(True)
        self.exp_category_list.setMaximumSize(QtCore.QSize(380, 100))
        self.exp_category_list.setStyleSheet("border: none;")
        self.exp_category_list.setIconSize(QtCore.QSize(60, 60))
        self.exp_category_list.setFlow(QtWidgets.QListView.LeftToRight)
        self.exp_category_list.setObjectName("exp_category_list")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/cafe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.exp_category_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/health.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.exp_category_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/meal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.exp_category_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/transport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.exp_category_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/other.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.exp_category_list.addItem(item)
        self.verticalLayout.addWidget(self.exp_category_list)
        self.add_exp_btn = QtWidgets.QPushButton(Form)
        self.add_exp_btn.setEnabled(True)
        self.add_exp_btn.setMinimumSize(QtCore.QSize(130, 30))
        self.add_exp_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.add_exp_btn.setStyleSheet("QPushButton{\n"
"    background-color: #2c7873;\n"
"    color: #021c1e;\n"
"    border: 2px solid #2c7873;\n"
"    border-radius: 15;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #5d9e9a;\n"
"    color: #021c1e;\n"
"    border: 2px solid #2c7873;\n"
"    border-radius: 15;\n"
"}")
        self.add_exp_btn.setCheckable(False)
        self.add_exp_btn.setDefault(False)
        self.add_exp_btn.setObjectName("add_exp_btn")
        self.verticalLayout.addWidget(self.add_exp_btn, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление операции"))
        self.amount_exp.setPlaceholderText(_translate("Form", "0"))
        __sortingEnabled = self.exp_category_list.isSortingEnabled()
        self.exp_category_list.setSortingEnabled(False)
        self.exp_category_list.setSortingEnabled(__sortingEnabled)
        self.add_exp_btn.setText(_translate("Form", "Добавить"))
