# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1384, 763)
        MainPage.setStyleSheet("background-color: #021c1e")
        self.gridLayout = QtWidgets.QGridLayout(MainPage)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(MainPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_of_pages = QtWidgets.QListWidget(self.frame)
        self.list_of_pages.setMinimumSize(QtCore.QSize(0, 0))
        self.list_of_pages.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.list_of_pages.setFont(font)
        self.list_of_pages.setStyleSheet("QListWidget {\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget:item {\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"}\n"
"\n"
"QListWidget:item:hover {\n"
"    background-color: rgba(111, 185, 143, 0.3);\n"
"    border-radius: 10px;\n"
"    color: #021c1e;\n"
"}\n"
"\n"
"QListWidget:item:!hover {\n"
"    background-color: #021c1e;\n"
"    color: white\n"
"}\n"
"\n"
"QListWidget:item:selected {\n"
"    background-color: #6fb98f;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.list_of_pages.setObjectName("list_of_pages")
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_of_pages.addItem(item)
        self.gridLayout_2.addWidget(self.list_of_pages, 1, 0, 1, 1)
        self.stacked_main_pages = QtWidgets.QStackedWidget(self.frame)
        self.stacked_main_pages.setObjectName("stacked_main_pages")
        self.diagramm_page = QtWidgets.QWidget()
        self.diagramm_page.setObjectName("diagramm_page")
        self.stacked_main_pages.addWidget(self.diagramm_page)
        self.schedule_page = QtWidgets.QWidget()
        self.schedule_page.setObjectName("schedule_page")
        self.stacked_main_pages.addWidget(self.schedule_page)
        self.regular_page = QtWidgets.QWidget()
        self.regular_page.setObjectName("regular_page")
        self.stacked_main_pages.addWidget(self.regular_page)
        self.converter_page = QtWidgets.QWidget()
        self.converter_page.setObjectName("converter_page")
        self.stacked_main_pages.addWidget(self.converter_page)
        self.exchange_page = QtWidgets.QWidget()
        self.exchange_page.setObjectName("exchange_page")
        self.stacked_main_pages.addWidget(self.exchange_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.stacked_main_pages.addWidget(self.settings_page)
        self.gridLayout_2.addWidget(self.stacked_main_pages, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #004445;\n"
"    border-bottom-left-radius: 30px;\n"
"    border-bottom-right-radius: 30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bill_info = QtWidgets.QGridLayout()
        self.bill_info.setHorizontalSpacing(10)
        self.bill_info.setObjectName("bill_info")
        self.list_of_accounts = QtWidgets.QComboBox(self.frame_2)
        self.list_of_accounts.setMinimumSize(QtCore.QSize(120, 0))
        self.list_of_accounts.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.list_of_accounts.setFont(font)
        self.list_of_accounts.setAutoFillBackground(False)
        self.list_of_accounts.setStyleSheet("QComboBox:drop-down {\n"
"    background-color: #2c7873;\n"
"}\n"
"QComboBox{\n"
"  color: white;    \n"
"  background-color: #2c7873;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"  border: none;\n"
"  height: 6px;\n"
"  width: 6px;\n"
"  margin: 0px;\n"
"    border-radius: 5px;\n"
"}")
        self.list_of_accounts.setIconSize(QtCore.QSize(16, 16))
        self.list_of_accounts.setDuplicatesEnabled(False)
        self.list_of_accounts.setObjectName("list_of_accounts")
        self.list_of_accounts.addItem("")
        self.list_of_accounts.addItem("")
        self.bill_info.addWidget(self.list_of_accounts, 0, 0, 1, 3)
        self.change_balance = QtWidgets.QPushButton(self.frame_2)
        self.change_balance.setMaximumSize(QtCore.QSize(21, 23))
        self.change_balance.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_balance.setIcon(icon)
        self.change_balance.setFlat(True)
        self.change_balance.setObjectName("change_balance")
        self.bill_info.addWidget(self.change_balance, 1, 2, 1, 1)
        self.balance_label = QtWidgets.QLabel(self.frame_2)
        self.balance_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.balance_label.setFont(font)
        self.balance_label.setStyleSheet("color: white")
        self.balance_label.setText("")
        self.balance_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balance_label.setObjectName("balance_label")
        self.bill_info.addWidget(self.balance_label, 1, 0, 1, 1)
        self.currency_label = QtWidgets.QLabel(self.frame_2)
        self.currency_label.setMinimumSize(QtCore.QSize(30, 0))
        self.currency_label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currency_label.setFont(font)
        self.currency_label.setStyleSheet("color: white")
        self.currency_label.setText("")
        self.currency_label.setObjectName("currency_label")
        self.bill_info.addWidget(self.currency_label, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.bill_info, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.profile_list_widget = QtWidgets.QListWidget(self.frame)
        self.profile_list_widget.setMaximumSize(QtCore.QSize(300, 80))
        self.profile_list_widget.setStyleSheet("border: none;\n"
"border-bottom: 2px ridge #6fb98f;")
        self.profile_list_widget.setObjectName("profile_list_widget")
        self.gridLayout_2.addWidget(self.profile_list_widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        __sortingEnabled = self.list_of_pages.isSortingEnabled()
        self.list_of_pages.setSortingEnabled(False)
        item = self.list_of_pages.item(0)
        item.setText(_translate("MainPage", "Диаграмма"))
        item = self.list_of_pages.item(1)
        item.setText(_translate("MainPage", "График"))
        item = self.list_of_pages.item(2)
        item.setText(_translate("MainPage", "Регулярные платежи"))
        item = self.list_of_pages.item(3)
        item.setText(_translate("MainPage", "Конвертер валют"))
        item = self.list_of_pages.item(4)
        item.setText(_translate("MainPage", "Курс валют"))
        item = self.list_of_pages.item(5)
        item.setText(_translate("MainPage", "Настройки"))
        self.list_of_pages.setSortingEnabled(__sortingEnabled)
        self.list_of_accounts.setItemText(0, _translate("MainPage", "aSas"))
        self.list_of_accounts.setItemText(1, _translate("MainPage", "ASasAS"))
