# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1384, 763)
        MainPage.setStyleSheet("background-color: #021c1e")
        self.gridLayout = QtWidgets.QGridLayout(MainPage)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(MainPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_of_pages = QtWidgets.QListWidget(self.frame)
        self.list_of_pages.setMinimumSize(QtCore.QSize(0, 0))
        self.list_of_pages.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.list_of_pages.setFont(font)
        self.list_of_pages.setStyleSheet("QListWidget {\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget:item {\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"}\n"
"\n"
"QListWidget:item:hover {\n"
"    background-color: rgba(111, 185, 143, 0.3);\n"
"    border-radius: 10px;\n"
"    color: #021c1e;\n"
"}\n"
"\n"
"QListWidget:item:!hover {\n"
"    background-color: #021c1e;\n"
"    color: white\n"
"}\n"
"\n"
"QListWidget:item:selected {\n"
"    background-color: #6fb98f;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.list_of_pages.setObjectName("list_of_pages")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/diagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/bar"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/regular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/converter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/exchange_rate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.list_of_pages.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.list_of_pages.addItem(item)
        self.gridLayout_2.addWidget(self.list_of_pages, 1, 0, 1, 1)
        self.profile_list_widget = QtWidgets.QListWidget(self.frame)
        self.profile_list_widget.setMaximumSize(QtCore.QSize(300, 80))
        self.profile_list_widget.setStyleSheet("\n"
"QListWidget {\n"
"    border: none;\n"
"    border-bottom: 2px ridge #6fb98f;\n"
"    color: white;\n"
"}\n"
"\n"
"QListWidget:item {\n"
"    padding-top: 25px;\n"
"    padding-bottom: 25px;\n"
"}\n"
"\n"
"QListWidget:item:hover {\n"
"    background-color: rgba(111, 185, 143, 0.3);\n"
"    border-radius: 10px;\n"
"    color: #021c1e;\n"
"}\n"
"\n"
"QListWidget:item:!hover {\n"
"    background-color: #021c1e;\n"
"    color: white\n"
"}\n"
"\n"
"")
        self.profile_list_widget.setObjectName("profile_list_widget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        item.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.profile_list_widget.addItem(item)
        self.gridLayout_2.addWidget(self.profile_list_widget, 0, 0, 1, 1)
        self.stacked_main_pages = QtWidgets.QStackedWidget(self.frame)
        self.stacked_main_pages.setObjectName("stacked_main_pages")
        self.diagramm_page = QtWidgets.QWidget()
        self.diagramm_page.setObjectName("diagramm_page")
        self.stacked_main_pages.addWidget(self.diagramm_page)
        self.schedule_page = QtWidgets.QWidget()
        self.schedule_page.setObjectName("schedule_page")
        self.stacked_main_pages.addWidget(self.schedule_page)
        self.regular_page = QtWidgets.QWidget()
        self.regular_page.setObjectName("regular_page")
        self.stacked_main_pages.addWidget(self.regular_page)
        self.converter_page = QtWidgets.QWidget()
        self.converter_page.setObjectName("converter_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.converter_page)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.available_currency = QtWidgets.QComboBox(self.converter_page)
        self.available_currency.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.available_currency.setFont(font)
        self.available_currency.setStyleSheet("QComboBox:drop-down {\n"
"    background-color: #2c7873;\n"
"}\n"
"QComboBox{\n"
"  color: white;    \n"
"  background-color: #2c7873;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"  border: none;\n"
"  height: 6px;\n"
"  width: 6px;\n"
"  margin: 0px;\n"
"    border-radius: 10px;\n"
"}")
        self.available_currency.setObjectName("available_currency")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.available_currency.addItem("")
        self.gridLayout_3.addWidget(self.available_currency, 1, 1, 1, 1)
        self.available_sum = QtWidgets.QLineEdit(self.converter_page)
        self.available_sum.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.available_sum.setFont(font)
        self.available_sum.setStyleSheet("border: 2px solid transparent;\n"
"border-bottom: 2px ridge #6fb98f;\n"
"color: white;\n"
"height: 30")
        self.available_sum.setObjectName("available_sum")
        self.gridLayout_3.addWidget(self.available_sum, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.converter_page)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.required_sum = QtWidgets.QLineEdit(self.converter_page)
        self.required_sum.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.required_sum.setFont(font)
        self.required_sum.setStyleSheet("border: 2px solid transparent;\n"
"border-bottom: 2px ridge #6fb98f;\n"
"color: white;\n"
"height: 30")
        self.required_sum.setReadOnly(True)
        self.required_sum.setObjectName("required_sum")
        self.gridLayout_3.addWidget(self.required_sum, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.available_currency_2 = QtWidgets.QComboBox(self.converter_page)
        self.available_currency_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.available_currency_2.setFont(font)
        self.available_currency_2.setStyleSheet("QComboBox:drop-down {\n"
"    background-color: #2c7873;\n"
"}\n"
"QComboBox{\n"
"  color: white;    \n"
"  background-color: #2c7873;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"  border: none;\n"
"  height: 6px;\n"
"  width: 6px;\n"
"  margin: 0px;\n"
"    border-radius: 10px;\n"
"}")
        self.available_currency_2.setObjectName("available_currency_2")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.available_currency_2.addItem("")
        self.gridLayout_3.addWidget(self.available_currency_2, 3, 1, 1, 1)
        self.stacked_main_pages.addWidget(self.converter_page)
        self.exchange_page = QtWidgets.QWidget()
        self.exchange_page.setObjectName("exchange_page")
        self.stacked_main_pages.addWidget(self.exchange_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.settings_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.quit_button = QtWidgets.QPushButton(self.settings_page)
        self.quit_button.setMinimumSize(QtCore.QSize(0, 40))
        self.quit_button.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("QPushButton{\n"
"    background-color: #2c7873;\n"
"    color: #021c1e;\n"
"    border: 2px solid #2c7873;\n"
"    border-radius: 20;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #5d9e9a;\n"
"    color: #021c1e;\n"
"    border: 2px solid #2c7873;\n"
"    border-radius: 20;\n"
"}")
        self.quit_button.setObjectName("quit_button")
        self.gridLayout_5.addWidget(self.quit_button, 0, 0, 1, 1)
        self.stacked_main_pages.addWidget(self.settings_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.profile_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.profile_picture = QtWidgets.QLabel(self.profile_page)
        self.profile_picture.setMinimumSize(QtCore.QSize(336, 0))
        self.profile_picture.setMaximumSize(QtCore.QSize(140, 140))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.profile_picture.setFont(font)
        self.profile_picture.setText("")
        self.profile_picture.setPixmap(QtGui.QPixmap("icons/user.png"))
        self.profile_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_picture.setObjectName("profile_picture")
        self.gridLayout_6.addWidget(self.profile_picture, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        self.account_description = QtWidgets.QLineEdit(self.profile_page)
        self.account_description.setMinimumSize(QtCore.QSize(0, 30))
        self.account_description.setStyleSheet("\n"
"    border: 2px solid transparent;\n"
"    border-bottom: 2px ridge #6fb98f;\n"
"    color: white;\n"
"")
        self.account_description.setObjectName("account_description")
        self.gridLayout_6.addWidget(self.account_description, 2, 1, 1, 1)
        self.current_email = QtWidgets.QLineEdit(self.profile_page)
        self.current_email.setMinimumSize(QtCore.QSize(0, 30))
        self.current_email.setStyleSheet("\n"
"    border: 2px solid transparent;\n"
"    border-bottom: 2px ridge #6fb98f;\n"
"    color: white;\n"
"")
        self.current_email.setReadOnly(True)
        self.current_email.setObjectName("current_email")
        self.gridLayout_6.addWidget(self.current_email, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.profile_page)
        self.label_2.setStyleSheet("color: white;\n"
"font: 9pt \"MS Reference Sans Serif\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.profile_page)
        self.label_3.setStyleSheet("color: white;\n"
"font: 9pt \"MS Reference Sans Serif\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.stacked_main_pages.addWidget(self.profile_page)
        self.gridLayout_2.addWidget(self.stacked_main_pages, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #004445;\n"
"    border-bottom-left-radius: 30px;\n"
"    border-bottom-right-radius: 30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bill_info = QtWidgets.QGridLayout()
        self.bill_info.setHorizontalSpacing(10)
        self.bill_info.setObjectName("bill_info")
        self.list_of_accounts = QtWidgets.QComboBox(self.frame_2)
        self.list_of_accounts.setMinimumSize(QtCore.QSize(120, 0))
        self.list_of_accounts.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.list_of_accounts.setFont(font)
        self.list_of_accounts.setAutoFillBackground(False)
        self.list_of_accounts.setStyleSheet("QComboBox:drop-down {\n"
"    background-color: #2c7873;\n"
"    color: white;\n"
"}\n"
"QComboBox{\n"
"  color: white;    \n"
"  background-color: #2c7873;\n"
"  padding: 10px;\n"
"  selection-background-color: #6fb98f;\n"
"  border: none;\n"
"  height: 6px;\n"
"  width: 6px;\n"
"  margin: 0px;\n"
"    border-radius: 5px;\n"
"}")
        self.list_of_accounts.setIconSize(QtCore.QSize(16, 16))
        self.list_of_accounts.setDuplicatesEnabled(False)
        self.list_of_accounts.setObjectName("list_of_accounts")
        self.list_of_accounts.addItem("")
        self.list_of_accounts.addItem("")
        self.bill_info.addWidget(self.list_of_accounts, 0, 0, 1, 3)
        self.change_balance = QtWidgets.QPushButton(self.frame_2)
        self.change_balance.setMaximumSize(QtCore.QSize(21, 23))
        self.change_balance.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_balance.setIcon(icon7)
        self.change_balance.setFlat(True)
        self.change_balance.setObjectName("change_balance")
        self.bill_info.addWidget(self.change_balance, 1, 2, 1, 1)
        self.balance_label = QtWidgets.QLabel(self.frame_2)
        self.balance_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.balance_label.setFont(font)
        self.balance_label.setStyleSheet("color: white")
        self.balance_label.setText("")
        self.balance_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balance_label.setObjectName("balance_label")
        self.bill_info.addWidget(self.balance_label, 1, 0, 1, 1)
        self.currency_label = QtWidgets.QLabel(self.frame_2)
        self.currency_label.setMinimumSize(QtCore.QSize(30, 0))
        self.currency_label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currency_label.setFont(font)
        self.currency_label.setStyleSheet("color: white")
        self.currency_label.setText("")
        self.currency_label.setObjectName("currency_label")
        self.bill_info.addWidget(self.currency_label, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.bill_info, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(MainPage)
        self.stacked_main_pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        __sortingEnabled = self.list_of_pages.isSortingEnabled()
        self.list_of_pages.setSortingEnabled(False)
        item = self.list_of_pages.item(0)
        item.setText(_translate("MainPage", "Диаграмма"))
        item = self.list_of_pages.item(1)
        item.setText(_translate("MainPage", "График"))
        item = self.list_of_pages.item(2)
        item.setText(_translate("MainPage", "Регулярные платежи"))
        item = self.list_of_pages.item(3)
        item.setText(_translate("MainPage", "Конвертер валют"))
        item = self.list_of_pages.item(4)
        item.setText(_translate("MainPage", "Курс валют"))
        item = self.list_of_pages.item(5)
        item.setText(_translate("MainPage", "Настройки"))
        self.list_of_pages.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.profile_list_widget.isSortingEnabled()
        self.profile_list_widget.setSortingEnabled(False)
        item = self.profile_list_widget.item(0)
        item.setText(_translate("MainPage", "Профиль"))
        self.profile_list_widget.setSortingEnabled(__sortingEnabled)
        self.available_currency.setCurrentText(_translate("MainPage", "Имеющаяся валюта:"))
        self.available_currency.setItemText(0, _translate("MainPage", "Имеющаяся валюта:"))
        self.available_currency.setItemText(1, _translate("MainPage", "EUR"))
        self.available_currency.setItemText(2, _translate("MainPage", "MTL"))
        self.available_currency.setItemText(3, _translate("MainPage", "ILS"))
        self.available_currency.setItemText(4, _translate("MainPage", "DKK"))
        self.available_currency.setItemText(5, _translate("MainPage", "SEK"))
        self.available_currency.setItemText(6, _translate("MainPage", "CHF"))
        self.available_currency.setItemText(7, _translate("MainPage", "EEK"))
        self.available_currency.setItemText(8, _translate("MainPage", "NZD"))
        self.available_currency.setItemText(9, _translate("MainPage", "JPY"))
        self.available_currency.setItemText(10, _translate("MainPage", "KRW"))
        self.available_currency.setItemText(11, _translate("MainPage", "SKK"))
        self.available_currency.setItemText(12, _translate("MainPage", "TRL"))
        self.available_currency.setItemText(13, _translate("MainPage", "ISK"))
        self.available_currency.setItemText(14, _translate("MainPage", "HKD"))
        self.available_currency.setItemText(15, _translate("MainPage", "LTL"))
        self.available_currency.setItemText(16, _translate("MainPage", "PHP"))
        self.available_currency.setItemText(17, _translate("MainPage", "CZK"))
        self.available_currency.setItemText(18, _translate("MainPage", "CYP"))
        self.available_currency.setItemText(19, _translate("MainPage", "BRL"))
        self.available_currency.setItemText(20, _translate("MainPage", "TRY"))
        self.available_currency.setItemText(21, _translate("MainPage", "AUD"))
        self.available_currency.setItemText(22, _translate("MainPage", "CAD"))
        self.available_currency.setItemText(23, _translate("MainPage", "MXN"))
        self.available_currency.setItemText(24, _translate("MainPage", "HUF"))
        self.available_currency.setItemText(25, _translate("MainPage", "THB"))
        self.available_currency.setItemText(26, _translate("MainPage", "ZAR"))
        self.available_currency.setItemText(27, _translate("MainPage", "BGN"))
        self.available_currency.setItemText(28, _translate("MainPage", "IDR"))
        self.available_currency.setItemText(29, _translate("MainPage", "LVL"))
        self.available_currency.setItemText(30, _translate("MainPage", "MYR"))
        self.available_currency.setItemText(31, _translate("MainPage", "GBP"))
        self.available_currency.setItemText(32, _translate("MainPage", "CNY"))
        self.available_currency.setItemText(33, _translate("MainPage", "SIT"))
        self.available_currency.setItemText(34, _translate("MainPage", "RUB"))
        self.available_currency.setItemText(35, _translate("MainPage", "SGD"))
        self.available_currency.setItemText(36, _translate("MainPage", "NOK"))
        self.available_currency.setItemText(37, _translate("MainPage", "RON"))
        self.available_currency.setItemText(38, _translate("MainPage", "HRK"))
        self.available_currency.setItemText(39, _translate("MainPage", "ROL"))
        self.available_currency.setItemText(40, _translate("MainPage", "INR"))
        self.available_currency.setItemText(41, _translate("MainPage", "PLN"))
        self.available_currency.setItemText(42, _translate("MainPage", "USD"))
        self.available_sum.setPlaceholderText(_translate("MainPage", "Имеющаяся сумма:"))
        self.label.setText(_translate("MainPage", "КОНВЕРТЕР ВАЛЮТ"))
        self.required_sum.setPlaceholderText(_translate("MainPage", "Вы получите:"))
        self.available_currency_2.setCurrentText(_translate("MainPage", "Нужная валюта:"))
        self.available_currency_2.setItemText(0, _translate("MainPage", "Нужная валюта:"))
        self.available_currency_2.setItemText(1, _translate("MainPage", "EUR"))
        self.available_currency_2.setItemText(2, _translate("MainPage", "MTL"))
        self.available_currency_2.setItemText(3, _translate("MainPage", "ILS"))
        self.available_currency_2.setItemText(4, _translate("MainPage", "DKK"))
        self.available_currency_2.setItemText(5, _translate("MainPage", "SEK"))
        self.available_currency_2.setItemText(6, _translate("MainPage", "CHF"))
        self.available_currency_2.setItemText(7, _translate("MainPage", "EEK"))
        self.available_currency_2.setItemText(8, _translate("MainPage", "NZD"))
        self.available_currency_2.setItemText(9, _translate("MainPage", "JPY"))
        self.available_currency_2.setItemText(10, _translate("MainPage", "KRW"))
        self.available_currency_2.setItemText(11, _translate("MainPage", "SKK"))
        self.available_currency_2.setItemText(12, _translate("MainPage", "TRL"))
        self.available_currency_2.setItemText(13, _translate("MainPage", "ISK"))
        self.available_currency_2.setItemText(14, _translate("MainPage", "HKD"))
        self.available_currency_2.setItemText(15, _translate("MainPage", "LTL"))
        self.available_currency_2.setItemText(16, _translate("MainPage", "PHP"))
        self.available_currency_2.setItemText(17, _translate("MainPage", "CZK"))
        self.available_currency_2.setItemText(18, _translate("MainPage", "CYP"))
        self.available_currency_2.setItemText(19, _translate("MainPage", "BRL"))
        self.available_currency_2.setItemText(20, _translate("MainPage", "TRY"))
        self.available_currency_2.setItemText(21, _translate("MainPage", "AUD"))
        self.available_currency_2.setItemText(22, _translate("MainPage", "CAD"))
        self.available_currency_2.setItemText(23, _translate("MainPage", "MXN"))
        self.available_currency_2.setItemText(24, _translate("MainPage", "HUF"))
        self.available_currency_2.setItemText(25, _translate("MainPage", "THB"))
        self.available_currency_2.setItemText(26, _translate("MainPage", "ZAR"))
        self.available_currency_2.setItemText(27, _translate("MainPage", "BGN"))
        self.available_currency_2.setItemText(28, _translate("MainPage", "IDR"))
        self.available_currency_2.setItemText(29, _translate("MainPage", "LVL"))
        self.available_currency_2.setItemText(30, _translate("MainPage", "MYR"))
        self.available_currency_2.setItemText(31, _translate("MainPage", "GBP"))
        self.available_currency_2.setItemText(32, _translate("MainPage", "CNY"))
        self.available_currency_2.setItemText(33, _translate("MainPage", "SIT"))
        self.available_currency_2.setItemText(34, _translate("MainPage", "RUB"))
        self.available_currency_2.setItemText(35, _translate("MainPage", "SGD"))
        self.available_currency_2.setItemText(36, _translate("MainPage", "NOK"))
        self.available_currency_2.setItemText(37, _translate("MainPage", "RON"))
        self.available_currency_2.setItemText(38, _translate("MainPage", "HRK"))
        self.available_currency_2.setItemText(39, _translate("MainPage", "ROL"))
        self.available_currency_2.setItemText(40, _translate("MainPage", "INR"))
        self.available_currency_2.setItemText(41, _translate("MainPage", "PLN"))
        self.available_currency_2.setItemText(42, _translate("MainPage", "USD"))
        self.quit_button.setText(_translate("MainPage", "Выйти из аккаунта"))
        self.label_2.setText(_translate("MainPage", "Ваш e-mail:      "))
        self.label_3.setText(_translate("MainPage", "Описание счета:      "))
        self.list_of_accounts.setItemText(0, _translate("MainPage", "aSas"))
        self.list_of_accounts.setItemText(1, _translate("MainPage", "ASasAS"))
